site_name: THUAI7

nav:
  - 背景与规则: index.md
  - 快速开始: quickstart.md
  - 前端使用说明: viewer.md
  - Python SDK: python_sdk.md
  - C++ SDK: C++_sdk.md
  - 常见问题: Q&A.md
theme:
  name: material
  
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
